---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Target: where our play will run and options it will run with
  hosts: ubuntu3,centos3

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Install EPEL
      yum:
        name: epel-release
        update_cache: yes
        state: latest
      when: ansible_distribution == 'CentOS'

    - name: Install Nginx
      package:
        name: nginx
        state: latest

    - name: Install Patch
      yum:
        name: patch
        update_cache: yes
        state: latest
      when: ansible_distribution == 'CentOS'

    - name: Patch nginx.conf to include sites-available, disable default server entry
      patch:
        src: files/nginx.conf.centos.patch
        dest: /etc/nginx/nginx.conf
      when: ansible_distribution == 'CentOS'

    - name: Create /etc/nginx/sites-available directory if required
      file:
        path: /etc/nginx/sites-available
        state: directory

    - name: Create /etc/nginx/sites-enabled directory if required
      file:
        path: /etc/nginx/sites-enabled
        state: directory

    - name: Copy default nginx configuration
      copy:
        src: files/nginx-default.conf
        dest: /etc/nginx/sites-available/default

    - name: Symbolic link /etc/nginx/sites-available/default to /etc/nginx/sites-enabled/default
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Create nginx/html directory if required
      file:
        path: /usr/share/nginx/html
        state: directory

# Three dots indicate the end of a YAML document
...
