---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
 
  # Target: where our play will run and options it will run with
  hosts: centos1
  gather_facts: true
 
  # Variable: variables that will apply to the play, on all target systems

  # Task: the list of tasks that will be executed within the playbook
  tasks:
    - name: Test hostvars with an ansible fact and collect ansible_port, dot notation
      debug:
        msg: "{{ hostvars[ansible_hostname].ansible_port }}"

    - name: Test hostvars with an ansible fact and collect ansible_port, dict notation
      debug:
        msg: "{{ hostvars[ansible_hostname]['ansible_port'] }}"
 
# Three dots indicate the end of a YAML document
...
